# Generated by Django 2.0.6 on 2018-06-19 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockProducer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=12)),
                ('producer_key', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
