# Generated by Django 2.0.6 on 2018-06-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockproducer',
            name='display_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
