# Generated by Django 2.0.6 on 2018-07-02 09:09

from django.db import migrations, models
import django.db.models.deletion
import tools.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('creator_url', models.URLField()),
                ('image', models.ImageField(upload_to=tools.models.dapp_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='DappCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to=tools.models.tool_directory_path)),
                ('creator_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.ToolCategory'),
        ),
        migrations.AddField(
            model_name='dapp',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.DappCategory'),
        ),
    ]
