# Generated by Django 2.0.6 on 2018-07-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20180702_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='dapp',
            name='status',
            field=models.CharField(choices=[('LIVE', 'LIVE'), ('PENDING', 'PENDING'), ('UNDER_DEV', 'UNDER_DEV')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('LIVE', 'LIVE'), ('PENDING', 'PENDING'), ('UNDER_DEV', 'UNDER_DEV')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
