# Generated by Django 2.0.6 on 2018-07-06 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20180702_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_category', to='tools.ToolCategory'),
        ),
    ]
