# Generated by Django 2.0.6 on 2018-07-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20180706_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='category',
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ManyToManyField(related_name='tool_category', to='tools.ToolCategory'),
        ),
    ]
