# Generated by Django 2.0.6 on 2018-07-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20180706_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='category',
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_category', to='tools.ToolCategory'),
        ),
    ]
