# Generated by Django 2.0.6 on 2018-07-06 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20180706_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedTool',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.Tool')),
            ],
            bases=('tools.tool',),
        ),
    ]
