# Generated by Django 2.0.6 on 2018-07-06 11:23

from django.db import migrations, models
import django.db.models.deletion
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_suggestedtool'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('creator_url', models.URLField()),
                ('image', models.ImageField(upload_to=tools.models.tool_directory_path)),
                ('about', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('LIVE', 'LIVE'), ('PENDING', 'PENDING'), ('UNDER_DEV', 'UNDER_DEV')], max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_cat', to='tools.ToolCategory')),
            ],
        ),
    ]
