# Generated by Django 2.0.6 on 2018-07-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_communitytool'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityTool',
            new_name='SuggestedCommunityTool',
        ),
    ]
