# Generated by Django 2.0.6 on 2018-06-16 23:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20180617_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content_test',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
