# Generated by Django 2.0.6 on 2018-06-16 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_question_content_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content_test',
        ),
    ]
