# Generated by Django 2.0.6 on 2018-06-18 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0007_auto_20180617_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='question',
            name='respondent',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
