# Generated by Django 2.0.6 on 2018-06-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0009_auto_20180619_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=14000),
        ),
    ]
