# Generated by Django 2.0.6 on 2018-06-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0011_auto_20180624_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
