# Generated by Django 2.0.6 on 2018-06-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0012_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
