# Generated by Django 2.0.6 on 2018-06-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0014_category_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='faq.Category'),
        ),
    ]
